# Generated by Django 3.1.2 on 2021-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
