# Generated by Django 3.1.2 on 2021-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210520_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
