# Generated by Django 3.1.2 on 2021-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210520_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
