# Generated by Django 3.1.2 on 2021-05-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20210520_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prof',
            field=models.ForeignKey(default='s', on_delete=django.db.models.deletion.CASCADE, to='manager.profile'),
        ),
    ]
