# Generated by Django 3.1.2 on 2021-05-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210520_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='a_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='prof',
        ),
    ]
