# Generated by Django 3.1.2 on 2021-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210520_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='a_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ManyToManyField(to='manager.Profile'),
        ),
    ]
