# Generated by Django 3.1.2 on 2021-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20210520_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
