# Generated by Django 3.1.2 on 2021-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20210525_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
