# Generated by Django 3.1.2 on 2021-06-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210601_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='love',
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('dislike', models.IntegerField(default=0)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.post')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.profile')),
            ],
        ),
    ]
